Задача 1(факториал)
js-tasks-ru/jsbasic-20220901_romanov9889 pull request #2
Opened 2022-09-06 22:42 UTC by romanov9889

2022-09-06 22:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-07 00:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-07 00:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-07 11:48 UTC, SinimaWath requested changes

2022-09-07 11:48 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  if (str.toLowerCase().indexOf(SPAM1) >= 0 || str.toLowerCase().indexOf(SPAM2) >= 0){
`str.toLowerCase().indexOf(SPAM1) >= 0 || str.toLowerCase().indexOf(SPAM2) >= 0` - и так возвращает boolean, потому if тут не нужен:
`return str.toLowerCase().indexOf(SPAM1) >= 0 || str.toLowerCase().indexOf(SPAM2) >= 0`

2022-09-07 11:48 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
else, тут лишний:
```
if (str.length < maxlength) {
  return str;
}

return str.slice(0, maxlength - 1) + '…';
```

2022-09-07 11:48 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return Boolean(str.length) ? str[0].toUpperCase() + str.slice(1) : str;
можно упростить до:
`return str ? str[0].toUpperCase() + str.slice(1) : str`

2022-09-07 12:31 UTC, romanov9889 commented on 1-module/3-task/index.js
> +  return Boolean(str.length) ? str[0].toUpperCase() + str.slice(1) : str;
Точно, думал, что пустая строка будет преобразовываться в true(перепутал с пробелом)

2022-09-07 12:40 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-07 13:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-08 14:21 UTC, SinimaWath approved these changes

2022-09-08 14:22 UTC, merged